/*
https://leetcode.com/problems/find-the-difference/?tab=Description
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/
/*
Solution:   https://leetcode.com/submissions/detail/83244786/
            Prepare a hashmap. First add counts to letters in map as found in s.
            Then substract count and delete keys in map as found in the t.
            Finally only 1 key with value 1 remains in the map.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
    hm = {};
    for ( var i in s) {
        if (hm[s[i]]) {
            hm[s[i]] = hm[s[i]] + 1;
        } else {
            hm[s[i]] = 1;
        }
    }
    for ( var j in t) {
        if (hm[t[j]]) {
            if (hm[t[j]] === 1) {
                delete hm[t[j]];
            } else {
                hm[t[j]] = hm[t[j]] - 1;
            }
        } else {
            hm[t[j]] = 1;
        }
    }
    for ( var k in hm) {
        if (hm[k] === 1) {
            return k;
        }
    }
};

var main = function () {
    var s = "milind";
    var t = "milindh";
    console.log(findTheDifference(s, t));
}

main();